import {
  FiMessageCircle, FiBarChart2, FiTarget,
  FiFeather, FiEdit3, FiGlobe, FiZap,
} from "react-icons/fi";

export const AGENTS = [
  {
    id: "clarifier",
    label: "Idea Clarifier",
    short: "IC",
    icon: FiMessageCircle,
    color: "#7F77DD",
    gradient: "linear-gradient(135deg,#7F77DD,#534AB7)",
    doneBg: "#f0fdf4",
    doneBorder: "#9FE1CB",
    doneColor: "#085041",
  },
  {
    id: "market",
    label: "Market Analysis",
    short: "MA",
    icon: FiBarChart2,
    color: "#378ADD",
    gradient: "linear-gradient(135deg,#378ADD,#185FA5)",
    doneBg: "#EBF5FF",
    doneBorder: "#B5D4F4",
    doneColor: "#0C447C",
  },
  {
    id: "marketing",
    label: "Marketing Plan",
    short: "MP",
    icon: FiTarget,
    color: "#16A34A",
    gradient: "linear-gradient(135deg,#16A34A,#166534)",
    doneBg: "#ECFDF3",
    doneBorder: "#9FE1CB",
    doneColor: "#14532D",
  },
  {
    id: "brand",
    label: "Brand Identity",
    short: "BI",
    icon: FiFeather,
    color: "#D4537E",
    gradient: "linear-gradient(135deg,#D4537E,#72243E)",
    doneBg: "#FBEAF0",
    doneBorder: "#F4C0D1",
    doneColor: "#72243E",
  },
  {
    id: "content",
    label: "Content Creator",
    short: "CC",
    icon: FiEdit3,
    color: "#D85A30",
    gradient: "linear-gradient(135deg,#D85A30,#712B13)",
    doneBg: "#FAECE7",
    doneBorder: "#F5C4B3",
    doneColor: "#712B13",
  },
  {
    id: "website",
    label: "Website Builder",
    short: "WB",
    icon: FiGlobe,
    color: "#185FA5",
    gradient: "linear-gradient(135deg,#185FA5,#042C53)",
    doneBg: "#EBF5FF",
    doneBorder: "#B5D4F4",
    doneColor: "#0C447C",
  },
  {
    id: "optimizer",
    label: "Optimizer",
    short: "OP",
    icon: FiZap,
    color: "#854F0B",
    gradient: "linear-gradient(135deg,#854F0B,#412402)",
    doneBg: "#FAEEDA",
    doneBorder: "#FAC775",
    doneColor: "#633806",
  },
];

export const getAgent = (id) => AGENTS.find((a) => a.id === id);
